### ISSUE TITLE
`ThinArc::with_arc_mut` is unsound

### ISSUE THREAD

**Issue by steffahn** [Manishearth/triomphe#107]
The length can be changed, allowing out-of-bounds access:
```rust
use triomphe::{Arc, ThinArc};

fn main() {
    let mut a = ThinArc::from_header_and_slice((), &[1, 2, 3]);
    a.with_arc_mut(|a| {
        let a = Arc::get_mut(a).unwrap();
        a.header.length = 1_000_000
    });
    println!("{:?}", a); // -> segfault
}
```
The whole `Arc` can be replaced, breaking ref-counts:
```rust
use triomphe::{Arc, ThinArc};

fn main() {
    let mut a = ThinArc::from_header_and_slice((), &[1, 2, 3]);
    let other = ThinArc::from_header_and_slice((), &[1, 2, 3]);
    let other = Arc::from_thin(other);
    let extracted = a.with_arc_mut(|a| std::mem::replace(a, other));
    println!("{:?}", a); // -> works
    drop(extracted);
    println!("{:?}", a); // -> use-after-free
}
```

---

I believe this can be contained with sufficiently enforced dynamic checks to prevent the UB… though it’s not a particularly elegant API anymore IMO, because I don’t think it’s possible to avoid even having to *abort* in some cases.

**Comment by Manishearth** [comment]
Ugh, this is another type I didn't design and never fully fixed up.

The issue here is that HeaderSlice/HeaderWithLength carries safety invariants with it when used this way, but the types otherwise do not carry such invariants. This isn't the best way to design this API.

I think the easiest thing to do is to remove this API, we could make it panic for now. In the long term, this should be switched to using a concrete internally private type that builds on top of HeaderSliceWithLength.

**Comment by Manishearth** [comment]
I'm also not opposed to doing the technically-breaking change of switching HeaderSlcieWithLength over to a concrete internally-private type and hoping for the best. This is a safety issue, some leeway in breaking changes is okay if we can limit the damage.
