### ISSUE TITLE
Please don't update the MSRV on minor update when being this high on the version number

### ISSUE THREAD

**Issue by RustyNova016** [Manishearth/triomphe#93]
v0.1.13 got a breaking change by inserting the MSRV in the cargo.toml. While I don't really mind it, 1.76 is a pretty new. Most crates haven't bumped to it yet. And so its breaking impact is quite high. 

So be weary next time as it will definitely breaks things.

On a side note, is it really the checked MSRV? Or just an arbitrary version?

**Comment by Manishearth** [comment]
The MSRV was inserted due to https://github.com/Manishearth/triomphe/pull/84, just that before that PR we didn't have an MSRV. People noticed their builds breaking and I added an MSRV so that they get a better error message.


So yes, that is the actual MSRV for this crate.

I'm quite aware of the fact that updating MSRV can break clients. 1.76 is three versions ago: that is reasonably old in my opinion. I'm not under the impression that triomphe is used in crates that are deep enough in depgraphs that an MSRV older than that is warranted.

I don't particularly plan on bumping MSRV super often, but the `ptr::eq` fix was a longrunning potential soundness issue that got fixed with a new API, which I consider important enough.

> Most crates haven't bumped to it yet. 

I'd be very surprised by this. Most crates don't maintain MSRV. This primarily affects CI jobs that pin versions, and even then I'd dispute "most". I don't think the impact of this is that high, and crates who have that impact ought to pin versions IMO.
